In [59]:
#by using selenium and webdriver we are extract the data from website
import pandas as pd
import selenium
from selenium import webdriver

In [60]:
#we are using chrome browser as default
driver = webdriver.Chrome("Chromedriver.exe")

In [61]:
#flipkart website
driver.get('https://www.flipkart.com/')

In [62]:
#by using click button 
search_btn = driver.find_element_by_xpath("//button[@class='_2KpZ6l _2doB4z']")
search_btn.click()

In [63]:
#we are searching for specific name
search_btn = driver.find_element_by_xpath("//div[@class='_3OO5Xc']/input")

In [64]:
#sending words to search
search_btn.send_keys("sneakers")

In [65]:
#click the search button
search_btn = driver.find_element_by_xpath("//button[@class='L0Z3Pu']")
search_btn.click()

In [66]:
#getting the url
urls = []
next_page = driver.find_elements_by_xpath('//nav[@class="yFHi8N"]/a')
for i in next_page:
    urls.append(i.get_attribute("href"))

In [73]:
len(urls)

11

In [74]:
brand=[]
price=[]
offer=[]
product_description=[]

In [77]:
#getting all the value
for i in range(0,3):
    for j in driver.find_elements_by_xpath('//div[@class="_2WkVRV"]'):
        brand.append(j.text)
    for k in driver.find_elements_by_xpath('//div[@class="_3Ay6Sb"]'):
        offer.append(k.text)
    for m in driver.find_elements_by_xpath('//div[@class="_30jeq3"]'):
        price.append(m.text)
    for l in driver.find_elements_by_xpath('//a[@class="IRpwTa"]'):
        product_description.append(l.text)

In [78]:
brand

['bluemaker',
 'oxpeo',
 'Robbie jones',
 'HOTSTYLE',
 'Numenzo',
 'Robbie jones',
 'aadi',
 'ORICUM',
 'Stefano Rads',
 'Shoes Bank',
 'BRUTON',
 'VIPSJAZZY',
 'Birde',
 'ARMADO',
 'VORII',
 '"trend"',
 'Robbie jones',
 'bluemaker',
 'Zsyto',
 'Wen Hawk',
 'World Wear Footwear',
 '3SIX5',
 'Numenzo',
 'World Wear Footwear',
 'restinfoot',
 'World Wear Footwear',
 'Magnolia',
 'HOTSTYLE',
 'Kraasa',
 'Jack Diamond',
 'World Wear Footwear',
 'Axter',
 'SCATCHITE',
 'BRUTON',
 'SPARX',
 'ROCKFIELD',
 'T-ROCK',
 'D-SNEAKERZ',
 'Jokatoo',
 'World Wear Footwear',
 'bluemaker',
 'oxpeo',
 'Robbie jones',
 'HOTSTYLE',
 'Numenzo',
 'Robbie jones',
 'aadi',
 'ORICUM',
 'Stefano Rads',
 'Shoes Bank',
 'BRUTON',
 'VIPSJAZZY',
 'Birde',
 'ARMADO',
 'VORII',
 '"trend"',
 'Robbie jones',
 'bluemaker',
 'Zsyto',
 'Wen Hawk',
 'World Wear Footwear',
 '3SIX5',
 'Numenzo',
 'World Wear Footwear',
 'restinfoot',
 'World Wear Footwear',
 'Magnolia',
 'HOTSTYLE',
 'Kraasa',
 'Jack Diamond',
 'World Wear Footwear',
 'Axter',
 'SCATCHITE',
 'BRUTON',
 'SPARX',
 'ROCKFIELD',
 'T-ROCK',
 'D-SNEAKERZ',
 'Jokatoo',
 'World Wear Footwear',
 'bluemaker',
 'oxpeo',
 'Robbie jones',
 'HOTSTYLE',
 'Numenzo',
 'Robbie jones',
 'aadi',
 'ORICUM',
 'Stefano Rads',
 'Shoes Bank',
 'BRUTON',
 'VIPSJAZZY',
 'Birde',
 'ARMADO',
 'VORII',
 '"trend"',
 'Robbie jones',
 'bluemaker',
 'Zsyto',
 'Wen Hawk',
 'World Wear Footwear',
 '3SIX5',
 'Numenzo',
 'World Wear Footwear',
 'restinfoot',
 'World Wear Footwear',
 'Magnolia',
 'HOTSTYLE',
 'Kraasa',
 'Jack Diamond',
 'World Wear Footwear',
 'Axter',
 'SCATCHITE',
 'BRUTON',
 'SPARX',
 'ROCKFIELD',
 'T-ROCK',
 'D-SNEAKERZ',
 'Jokatoo',
 'World Wear Footwear']

In [79]:
product_description

['casual for men (blue 09) Sneakers For Men',
 'Colourblocked Trending Multicolor Ultralight canvas Spo...',
 'Casual Sneakers Shoes For Men Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Combo pack of 2 casual sneaker shoes for men Sneakers F...',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Combo Pack Of 4 Canvas Sneakers For Men',
 'Combo Pack of 4 Casual Shoes Sneakers For Men',
 'casual shoes For Mens Combo(AR)-1658-1619 ( Multicolor-...',
 'Latest Stylish Casual sneakers for men | Lace up lightw...',
 'Fashionable casual sneakers shoes for men Sneakers For ...',
 'Casual Sneakers Black Shoes For Men Sneakers For Men',
 'casual for men (blue 06) Sneakers For Men',
 'Latest Stylish Casual sneakers for men | Lace up lightw...',
 'Combo Pack of 4 Latest Collection Stylish Casual Loafer...',
 'ORIFWSH(OR)-1077 Sneakers For Men',
 'Casual Sneaker Sneakers For Men',
 'Men-9097 Latest Collection of Stylish Casual Comfortabl...',
 'Casual shoes Sneakers For Men',
 'Men 5014 Latest Collection Stylish Casual Sports Loafer...',
 'White Sneakers Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Series 7 Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'Combo Pack of 2 Latest Collection Stylish Casual Loafer...',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 'SM-482 Sneakers For Men',
 'Sneakers For Men',
 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'casual for men (blue 09) Sneakers For Men',
 'Colourblocked Trending Multicolor Ultralight canvas Spo...',
 'Casual Sneakers Shoes For Men Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Combo pack of 2 casual sneaker shoes for men Sneakers F...',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Combo Pack Of 4 Canvas Sneakers For Men',
 'Combo Pack of 4 Casual Shoes Sneakers For Men',
 'casual shoes For Mens Combo(AR)-1658-1619 ( Multicolor-...',
 'Latest Stylish Casual sneakers for men | Lace up lightw...',
 'Fashionable casual sneakers shoes for men Sneakers For ...',
 'Casual Sneakers Black Shoes For Men Sneakers For Men',
 'casual for men (blue 06) Sneakers For Men',
 'Latest Stylish Casual sneakers for men | Lace up lightw...',
 'Combo Pack of 4 Latest Collection Stylish Casual Loafer...',
 'ORIFWSH(OR)-1077 Sneakers For Men',
 'Casual Sneaker Sneakers For Men',
 'Men-9097 Latest Collection of Stylish Casual Comfortabl...',
 'Casual shoes Sneakers For Men',
 'Men 5014 Latest Collection Stylish Casual Sports Loafer...',
 'White Sneakers Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Series 7 Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'Combo Pack of 2 Latest Collection Stylish Casual Loafer...',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 'SM-482 Sneakers For Men',
 'Sneakers For Men',
 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'casual for men (blue 09) Sneakers For Men',
 'Colourblocked Trending Multicolor Ultralight canvas Spo...',
 'Casual Sneakers Shoes For Men Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Sneakers For Men',
 'Combo pack of 2 casual sneaker shoes for men Sneakers F...',
 "White Sneaker For Men's/Boy's Sneakers For Men",
 'Combo Pack Of 4 Canvas Sneakers For Men',
 'Combo Pack of 4 Casual Shoes Sneakers For Men',
 'casual shoes For Mens Combo(AR)-1658-1619 ( Multicolor-...',
 'Latest Stylish Casual sneakers for men | Lace up lightw...',
 'Fashionable casual sneakers shoes for men Sneakers For ...',
 'Casual Sneakers Black Shoes For Men Sneakers For Men',
 'casual for men (blue 06) Sneakers For Men',
 'Latest Stylish Casual sneakers for men | Lace up lightw...',
 'Combo Pack of 4 Latest Collection Stylish Casual Loafer...',
 'ORIFWSH(OR)-1077 Sneakers For Men',
 'Casual Sneaker Sneakers For Men',
 'Men-9097 Latest Collection of Stylish Casual Comfortabl...',
 'Casual shoes Sneakers For Men',
 'Men 5014 Latest Collection Stylish Casual Sports Loafer...',
 'White Sneakers Sneakers For Men',
 'Sneakers Sneakers For Men',
 'Series 7 Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...',
 'Combo Pack of 2 Latest Collection Stylish Casual Loafer...',
 'Sneakers Sneakers For Men',
 'Sneakers For Men',
 'SM-482 Sneakers For Men',
 'Sneakers For Men',
 'Synthetic Leather Casual Partywear Wedding Sneakers Sho...',
 "Casual , Partywear Sneakers Shoes For Men's And Boys Wh...",
 'Sneakers For Men',
 '5011-Latest Collection Stylish Casual Loafer Sneakers S...']

In [80]:
price

['₹474',
 '₹419',
 '₹379',
 '₹283',
 '₹398',
 '₹474',
 '₹399',
 '₹377',
 '₹242',
 '₹331',
 '₹499',
 '₹419',
 '₹842',
 '₹498',
 '₹399',
 '₹449',
 '₹428',
 '₹474',
 '₹328',
 '₹398',
 '₹499',
 '₹214',
 '₹539',
 '₹348',
 '₹379',
 '₹240',
 '₹305',
 '₹299',
 '₹416',
 '₹639',
 '₹240',
 '₹299',
 '₹398',
 '₹299',
 '₹965',
 '₹399',
 '₹378',
 '₹367',
 '₹455',
 '₹273',
 '₹474',
 '₹419',
 '₹379',
 '₹283',
 '₹398',
 '₹474',
 '₹399',
 '₹377',
 '₹242',
 '₹331',
 '₹499',
 '₹419',
 '₹842',
 '₹498',
 '₹399',
 '₹449',
 '₹428',
 '₹474',
 '₹328',
 '₹398',
 '₹499',
 '₹214',
 '₹539',
 '₹348',
 '₹379',
 '₹240',
 '₹305',
 '₹299',
 '₹416',
 '₹639',
 '₹240',
 '₹299',
 '₹398',
 '₹299',
 '₹965',
 '₹399',
 '₹378',
 '₹367',
 '₹455',
 '₹273',
 '₹474',
 '₹419',
 '₹379',
 '₹283',
 '₹398',
 '₹474',
 '₹399',
 '₹377',
 '₹242',
 '₹331',
 '₹499',
 '₹419',
 '₹842',
 '₹498',
 '₹399',
 '₹449',
 '₹428',
 '₹474',
 '₹328',
 '₹398',
 '₹499',
 '₹214',
 '₹539',
 '₹348',
 '₹379',
 '₹240',
 '₹305',
 '₹299',
 '₹416',
 '₹639',
 '₹240',
 '₹299',
 '₹398',
 '₹299',
 '₹965',
 '₹399',
 '₹378',
 '₹367',
 '₹455',
 '₹273']

In [81]:
offer

['52% off',
 '58% off',
 '62% off',
 '43% off',
 '60% off',
 '52% off',
 '60% off',
 '62% off',
 '65% off',
 '66% off',
 '85% off',
 '58% off',
 '57% off',
 '50% off',
 '60% off',
 '77% off',
 '57% off',
 '52% off',
 '74% off',
 '60% off',
 '81% off',
 '57% off',
 '46% off',
 '65% off',
 '62% off',
 '51% off',
 '69% off',
 '40% off',
 '58% off',
 '36% off',
 '51% off',
 '78% off',
 '60% off',
 '76% off',
 '28% off',
 '60% off',
 '62% off',
 '44% off',
 '69% off',
 '45% off',
 '52% off',
 '58% off',
 '62% off',
 '43% off',
 '60% off',
 '52% off',
 '60% off',
 '62% off',
 '65% off',
 '66% off',
 '85% off',
 '58% off',
 '57% off',
 '50% off',
 '60% off',
 '77% off',
 '57% off',
 '52% off',
 '74% off',
 '60% off',
 '81% off',
 '57% off',
 '46% off',
 '65% off',
 '62% off',
 '51% off',
 '69% off',
 '40% off',
 '58% off',
 '36% off',
 '51% off',
 '78% off',
 '60% off',
 '76% off',
 '28% off',
 '60% off',
 '62% off',
 '44% off',
 '69% off',
 '45% off',
 '52% off',
 '58% off',
 '62% off',
 '43% off',
 '60% off',
 '52% off',
 '60% off',
 '62% off',
 '65% off',
 '66% off',
 '85% off',
 '58% off',
 '57% off',
 '50% off',
 '60% off',
 '77% off',
 '57% off',
 '52% off',
 '74% off',
 '60% off',
 '81% off',
 '57% off',
 '46% off',
 '65% off',
 '62% off',
 '51% off',
 '69% off',
 '40% off',
 '58% off',
 '36% off',
 '51% off',
 '78% off',
 '60% off',
 '76% off',
 '28% off',
 '60% off',
 '62% off',
 '44% off',
 '69% off',
 '45% off',
 '52% off',
 '58% off',
 '62% off',
 '43% off',
 '60% off',
 '52% off',
 '60% off',
 '62% off',
 '65% off',
 '66% off',
 '85% off',
 '58% off',
 '57% off',
 '50% off',
 '60% off',
 '77% off',
 '57% off',
 '52% off',
 '74% off',
 '60% off',
 '81% off',
 '57% off',
 '46% off',
 '65% off',
 '62% off',
 '51% off',
 '69% off',
 '40% off',
 '58% off',
 '36% off',
 '51% off',
 '78% off',
 '60% off',
 '76% off',
 '28% off',
 '60% off',
 '62% off',
 '44% off',
 '69% off',
 '45% off',
 '52% off',
 '58% off',
 '62% off',
 '43% off',
 '60% off',
 '52% off',
 '60% off',
 '62% off',
 '65% off',
 '66% off',
 '85% off',
 '58% off',
 '57% off',
 '50% off',
 '60% off',
 '77% off',
 '57% off',
 '52% off',
 '74% off',
 '60% off',
 '81% off',
 '57% off',
 '46% off',
 '65% off',
 '62% off',
 '51% off',
 '69% off',
 '40% off',
 '58% off',
 '36% off',
 '51% off',
 '78% off',
 '60% off',
 '76% off',
 '28% off',
 '60% off',
 '62% off',
 '44% off',
 '69% off',
 '45% off',
 '52% off',
 '58% off',
 '62% off',
 '43% off',
 '60% off',
 '52% off',
 '60% off',
 '62% off',
 '65% off',
 '66% off',
 '85% off',
 '58% off',
 '57% off',
 '50% off',
 '60% off',
 '77% off',
 '57% off',
 '52% off',
 '74% off',
 '60% off',
 '81% off',
 '57% off',
 '46% off',
 '65% off',
 '62% off',
 '51% off',
 '69% off',
 '40% off',
 '58% off',
 '36% off',
 '51% off',
 '78% off',
 '60% off',
 '76% off',
 '28% off',
 '60% off',
 '62% off',
 '44% off',
 '69% off',
 '45% off']

In [82]:
print(len(brand),len(product_description),len(offer),len(price))

120 108 240 120

In [84]:
#form the data frame 
stock=pd.DataFrame({})
stock['brand']=brand
#stock['product_description']=product_description
#stock['offer']=offer
stock['price']=price

In [86]:
df=stock.head(100)

In [87]:
df

           brand price
0      bluemaker  ₹474
1          oxpeo  ₹419
2   Robbie jones  ₹379
3       HOTSTYLE  ₹283
4        Numenzo  ₹398
..           ...   ...
95       "trend"  ₹449
96  Robbie jones  ₹428
97     bluemaker  ₹474
98         Zsyto  ₹328
99      Wen Hawk  ₹398

[100 rows x 2 columns]