In [245]:
#by using selenium and webdriver we are extract the data from website
import pandas as pd
import selenium
from selenium import webdriver
import time

In [246]:
#we are using chrome browser as default
driver = webdriver.Chrome("Chromedriver.exe")

In [247]:
#myntra website
url = 'https://www.myntra.com/'
driver.get(url)

In [248]:
#we are searching for specific name
search_btn = driver.find_element_by_xpath("//div[@class='desktop-query']/input")

In [249]:
#sending words to search
search_btn.send_keys("shoes")

In [250]:
#sending words to search
search_btn = driver.find_element_by_xpath("//a[@class='desktop-submit']")
search_btn.click()

In [251]:
url = 'https://www.myntra.com/shoes?f=Color:Black_36454f&plaEnabled=false&rf=Price:6612.0_13075.0_6612.0 TO 13075.0'

In [252]:
driver.get(url)

In [253]:
#urls

In [254]:
urls = []
for i in range(0,9):
    for j in driver.find_elements_by_xpath('//li[@class="pagination-active"]/a'):
        urls.append(j.get_attribute("href"))
    driver.find_element_by_xpath('//li[@class="pagination-next"]/a').click()
    time.sleep(4)

In [255]:
#getting the url
urls

['https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0&p=2',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0&p=3',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0&p=4',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0&p=5',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0&p=6',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0&p=7',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0&p=8',
 'https://www.myntra.com/shoes?f=Color%3ABlack_36454f&plaEnabled=false&rf=Price%3A6612.0_13075.0_6612.0%20TO%2013075.0&p=9']

In [256]:
shoe_name =[]
price_of_shoe = []
description_of_shoe = []

In [257]:
for i in range(0,3):
    for j in driver.find_elements_by_xpath('//h3[@class="product-brand"]'):
        shoe_name.append(j.text)
    for k in driver.find_elements_by_xpath('//h4[@class="product-product"]'):
        description_of_shoe.append(k.text)
    for l in driver.find_elements_by_xpath('//div[@class="product-price"]'):
        price_of_shoe.append(l.text)

In [258]:
shoe_name

['Regal',
 'Regal',
 'J.FONTINI',
 'J.FONTINI',
 'Onitsuka Tiger',
 'Kenneth Cole',
 'Kenneth Cole',
 'Birkenstock',
 'Birkenstock',
 'Florsheim',
 'Geox',
 'Reebok',
 'ALDO',
 'Puma',
 'Supra',
 'JOHNSTON & MURPHY',
 'Bugatti',
 'Clarks',
 'ADIDAS Originals',
 'UNDER ARMOUR',
 'Reebok',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'ADIDAS Originals',
 'Nike',
 'ROSSO BRUNELLO',
 'ROSSO BRUNELLO',
 'ALDO',
 'Puma',
 'Nike',
 'UNDER ARMOUR',
 'Nike',
 'Nike',
 'DIESEL',
 'UNDER ARMOUR',
 'FILA',
 'Skechers',
 'Puma',
 'Puma',
 'Vans',
 'ADIDAS Originals',
 'Onitsuka Tiger',
 'ROSSO BRUNELLO',
 'Steve Madden',
 'ROSSO BRUNELLO',
 'Florsheim',
 'ROSSO BRUNELLO',
 'DAVINCHI',
 'ROSSO BRUNELLO',
 'UNDER ARMOUR',
 'Regal',
 'Regal',
 'J.FONTINI',
 'J.FONTINI',
 'Onitsuka Tiger',
 'Kenneth Cole',
 'Kenneth Cole',
 'Birkenstock',
 'Birkenstock',
 'Florsheim',
 'Geox',
 'Reebok',
 'ALDO',
 'Puma',
 'Supra',
 'JOHNSTON & MURPHY',
 'Bugatti',
 'Clarks',
 'ADIDAS Originals',
 'UNDER ARMOUR',
 'Reebok',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'ADIDAS Originals',
 'Nike',
 'ROSSO BRUNELLO',
 'ROSSO BRUNELLO',
 'ALDO',
 'Puma',
 'Nike',
 'UNDER ARMOUR',
 'Nike',
 'Nike',
 'DIESEL',
 'UNDER ARMOUR',
 'FILA',
 'Skechers',
 'Puma',
 'Puma',
 'Vans',
 'ADIDAS Originals',
 'Onitsuka Tiger',
 'ROSSO BRUNELLO',
 'Steve Madden',
 'ROSSO BRUNELLO',
 'Florsheim',
 'ROSSO BRUNELLO',
 'DAVINCHI',
 'ROSSO BRUNELLO',
 'UNDER ARMOUR',
 'Regal',
 'Regal',
 'J.FONTINI',
 'J.FONTINI',
 'Onitsuka Tiger',
 'Kenneth Cole',
 'Kenneth Cole',
 'Birkenstock',
 'Birkenstock',
 'Florsheim',
 'Geox',
 'Reebok',
 'ALDO',
 'Puma',
 'Supra',
 'JOHNSTON & MURPHY',
 'Bugatti',
 'Clarks',
 'ADIDAS Originals',
 'UNDER ARMOUR',
 'Reebok',
 'UNDER ARMOUR',
 'UNDER ARMOUR',
 'ADIDAS Originals',
 'Nike',
 'ROSSO BRUNELLO',
 'ROSSO BRUNELLO',
 'ALDO',
 'Puma',
 'Nike',
 'UNDER ARMOUR',
 'Nike',
 'Nike',
 'DIESEL',
 'UNDER ARMOUR',
 'FILA',
 'Skechers',
 'Puma',
 'Puma',
 'Vans',
 'ADIDAS Originals',
 'Onitsuka Tiger',
 'ROSSO BRUNELLO',
 'Steve Madden',
 'ROSSO BRUNELLO',
 'Florsheim',
 'ROSSO BRUNELLO',
 'DAVINCHI',
 'ROSSO BRUNELLO',
 'UNDER ARMOUR']

In [259]:
price_of_shoe

['Rs. 6742Rs. 8990(25% OFF)',
 'Rs. 6742Rs. 8990(25% OFF)',
 'Rs. 7990',
 'Rs. 7990',
 'Rs. 10999',
 'Rs. 8393Rs. 11990(30% OFF)',
 'Rs. 9513Rs. 13590(30% OFF)',
 'Rs. 10990',
 'Rs. 11990',
 'Rs. 9995',
 'Rs. 7199Rs. 11999(40% OFF)',
 'Rs. 9899Rs. 17999(45% OFF)',
 'Rs. 6999Rs. 13999(50% OFF)',
 'Rs. 6999',
 'Rs. 9499',
 'Rs. 7699Rs. 10999( 30 % OFF)',
 'Rs. 10499',
 'Rs. 7999',
 'Rs. 8399Rs. 13999( 40 % OFF)',
 'Rs. 7499',
 'Rs. 8999',
 'Rs. 8249Rs. 10999(25% OFF)',
 'Rs. 10199Rs. 11999(15% OFF)',
 'Rs. 7799Rs. 12999( 40 % OFF)',
 'Rs. 6636Rs. 8295(20% OFF)',
 'Rs. 10799Rs. 11999(10% OFF)',
 'Rs. 10349Rs. 11499(10% OFF)',
 'Rs. 9099Rs. 12999(30% OFF)',
 'Rs. 7149Rs. 12999(45% OFF)',
 'Rs. 8295',
 'Rs. 12499',
 'Rs. 12495',
 'Rs. 7206Rs. 10295( 30 % OFF)',
 'Rs. 9093Rs. 12990( 30 % OFF)',
 'Rs. 11999',
 'Rs. 7999',
 'Rs. 6999',
 'Rs. 7199Rs. 8999(20% OFF)',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 7699Rs. 13999( 45 % OFF)',
 'Rs. 8999',
 'Rs. 7199Rs. 7999(10% OFF)',
 'Rs. 6749Rs. 8999(25% OFF)',
 'Rs. 6999Rs. 9999(30% OFF)',
 'Rs. 6996Rs. 9995(30% OFF)',
 'Rs. 7699Rs. 10999(30% OFF)',
 'Rs. 7191Rs. 7990(10% OFF)',
 'Rs. 7699Rs. 10999(30% OFF)',
 'Rs. 10999',
 'Rs. 6742Rs. 8990(25% OFF)',
 'Rs. 6742Rs. 8990(25% OFF)',
 'Rs. 7990',
 'Rs. 7990',
 'Rs. 10999',
 'Rs. 8393Rs. 11990(30% OFF)',
 'Rs. 9513Rs. 13590(30% OFF)',
 'Rs. 10990',
 'Rs. 11990',
 'Rs. 9995',
 'Rs. 7199Rs. 11999(40% OFF)',
 'Rs. 9899Rs. 17999(45% OFF)',
 'Rs. 6999Rs. 13999(50% OFF)',
 'Rs. 6999',
 'Rs. 9499',
 'Rs. 7699Rs. 10999( 30 % OFF)',
 'Rs. 10499',
 'Rs. 7999',
 'Rs. 8399Rs. 13999( 40 % OFF)',
 'Rs. 7499',
 'Rs. 8999',
 'Rs. 8249Rs. 10999(25% OFF)',
 'Rs. 10199Rs. 11999(15% OFF)',
 'Rs. 7799Rs. 12999( 40 % OFF)',
 'Rs. 6636Rs. 8295(20% OFF)',
 'Rs. 10799Rs. 11999(10% OFF)',
 'Rs. 10349Rs. 11499(10% OFF)',
 'Rs. 9099Rs. 12999(30% OFF)',
 'Rs. 7149Rs. 12999(45% OFF)',
 'Rs. 8295',
 'Rs. 12499',
 'Rs. 12495',
 'Rs. 7206Rs. 10295( 30 % OFF)',
 'Rs. 9093Rs. 12990( 30 % OFF)',
 'Rs. 11999',
 'Rs. 7999',
 'Rs. 6999',
 'Rs. 7199Rs. 8999(20% OFF)',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 7699Rs. 13999( 45 % OFF)',
 'Rs. 8999',
 'Rs. 7199Rs. 7999(10% OFF)',
 'Rs. 6749Rs. 8999(25% OFF)',
 'Rs. 6999Rs. 9999(30% OFF)',
 'Rs. 6996Rs. 9995(30% OFF)',
 'Rs. 7699Rs. 10999(30% OFF)',
 'Rs. 7191Rs. 7990(10% OFF)',
 'Rs. 7699Rs. 10999(30% OFF)',
 'Rs. 10999',
 'Rs. 6742Rs. 8990(25% OFF)',
 'Rs. 6742Rs. 8990(25% OFF)',
 'Rs. 7990',
 'Rs. 7990',
 'Rs. 10999',
 'Rs. 8393Rs. 11990(30% OFF)',
 'Rs. 9513Rs. 13590(30% OFF)',
 'Rs. 10990',
 'Rs. 11990',
 'Rs. 9995',
 'Rs. 7199Rs. 11999(40% OFF)',
 'Rs. 9899Rs. 17999(45% OFF)',
 'Rs. 6999Rs. 13999(50% OFF)',
 'Rs. 6999',
 'Rs. 9499',
 'Rs. 7699Rs. 10999( 30 % OFF)',
 'Rs. 10499',
 'Rs. 7999',
 'Rs. 8399Rs. 13999( 40 % OFF)',
 'Rs. 7499',
 'Rs. 8999',
 'Rs. 8249Rs. 10999(25% OFF)',
 'Rs. 10199Rs. 11999(15% OFF)',
 'Rs. 7799Rs. 12999( 40 % OFF)',
 'Rs. 6636Rs. 8295(20% OFF)',
 'Rs. 10799Rs. 11999(10% OFF)',
 'Rs. 10349Rs. 11499(10% OFF)',
 'Rs. 9099Rs. 12999(30% OFF)',
 'Rs. 7149Rs. 12999(45% OFF)',
 'Rs. 8295',
 'Rs. 12499',
 'Rs. 12495',
 'Rs. 7206Rs. 10295( 30 % OFF)',
 'Rs. 9093Rs. 12990( 30 % OFF)',
 'Rs. 11999',
 'Rs. 7999',
 'Rs. 6999',
 'Rs. 7199Rs. 8999(20% OFF)',
 'Rs. 9999',
 'Rs. 9999',
 'Rs. 7699Rs. 13999( 45 % OFF)',
 'Rs. 8999',
 'Rs. 7199Rs. 7999(10% OFF)',
 'Rs. 6749Rs. 8999(25% OFF)',
 'Rs. 6999Rs. 9999(30% OFF)',
 'Rs. 6996Rs. 9995(30% OFF)',
 'Rs. 7699Rs. 10999(30% OFF)',
 'Rs. 7191Rs. 7990(10% OFF)',
 'Rs. 7699Rs. 10999(30% OFF)',
 'Rs. 10999']

In [260]:
description_of_shoe

['Men Leather Loafers',
 '',
 'Men Textured Leather Formal Loafers',
 'Men Leather Loafers',
 'Unisex Sneakers',
 'Men Solid Leather Formal Derbys',
 'Men Solid Leather Formal Oxfords',
 'Women Leather London Sneakers',
 'Leather Buckled Wedges',
 'Men Solid Leather Formal Brogues',
 'Women Leather Mid-Top Boots',
 'Men Float Ride Run 2.0',
 'Men Leather Derbys',
 'Women Basket Exotic Sneakers',
 'Men SKYTOP V Sneakers',
 'Men Derbys',
 'Men Solid Leather Formal Derbys',
 'Men Watts Pace Leather Derbys',
 'Men NITE JOGGER Sneakers',
 'Men Remix 2.0 Sportstyle Shoes',
 'Unisex Zig Kinetica 21 Running',
 'Men Liquify Running Shoes',
 'Men HOVR Guardian Shoes',
 'Men Solid NMD_R1 Sneakers',
 'Men AIR MAX INFINITY 2 Sneaker',
 'Men Solid Patent Leather Formal Loafers',
 'Men Solid Leather Formal Oxfords',
 'Men Solid Sneakers',
 'Men Running Shoes',
 'Unisex LEBRON Basketball Shoes',
 'Men Valsetz RTS 1.5 Trekking',
 'Men LEBRON 14 Basketball Shoes',
 'Men AIR ZOOM Running Shoes',
 'Men Sneakers',
 'TriBase Reign 2 Training Shoes',
 'Women Printed Sneakers',
 'Men SKECH-AIR STRATUS Sneakers',
 'Men LQDCELL Optic Shoes',
 'Unisex Textile Rise XT NETFIT 1 Baseball Shoes',
 'Men Solid Sneakers',
 'Women NMD_R1 PK Sneakers',
 'Unisex Leather Mexico 66 Sneakers',
 'Women Embellished Slim Heels',
 'Women Mid-Top Leather Heels',
 'Men Derbys Casual Shoes',
 'Men Solid Leather Formal Derbys',
 'Men Solid Leather Formal Monks',
 'Men Solid Formal Leather Loafers',
 'Men Solid Leather Formal Loafers',
 'Men HOVR Sonic 3 Running Shoes',
 'Men Leather Loafers',
 '',
 'Men Textured Leather Formal Loafers',
 'Men Leather Loafers',
 'Unisex Sneakers',
 'Men Solid Leather Formal Derbys',
 'Men Solid Leather Formal Oxfords',
 'Women Leather London Sneakers',
 'Leather Buckled Wedges',
 'Men Solid Leather Formal Brogues',
 'Women Leather Mid-Top Boots',
 'Men Float Ride Run 2.0',
 'Men Leather Derbys',
 'Women Basket Exotic Sneakers',
 'Men SKYTOP V Sneakers',
 'Men Derbys',
 'Men Solid Leather Formal Derbys',
 'Men Watts Pace Leather Derbys',
 'Men NITE JOGGER Sneakers',
 'Men Remix 2.0 Sportstyle Shoes',
 'Unisex Zig Kinetica 21 Running',
 'Men Liquify Running Shoes',
 'Men HOVR Guardian Shoes',
 'Men Solid NMD_R1 Sneakers',
 'Men AIR MAX INFINITY 2 Sneaker',
 'Men Solid Patent Leather Formal Loafers',
 'Men Solid Leather Formal Oxfords',
 'Men Solid Sneakers',
 'Men Running Shoes',
 'Unisex LEBRON Basketball Shoes',
 'Men Valsetz RTS 1.5 Trekking',
 'Men LEBRON 14 Basketball Shoes',
 'Men AIR ZOOM Running Shoes',
 'Men Sneakers',
 'TriBase Reign 2 Training Shoes',
 'Women Printed Sneakers',
 'Men SKECH-AIR STRATUS Sneakers',
 'Men LQDCELL Optic Shoes',
 'Unisex Textile Rise XT NETFIT 1 Baseball Shoes',
 'Men Solid Sneakers',
 'Women NMD_R1 PK Sneakers',
 'Unisex Leather Mexico 66 Sneakers',
 'Women Embellished Slim Heels',
 'Women Mid-Top Leather Heels',
 'Men Derbys Casual Shoes',
 'Men Solid Leather Formal Derbys',
 'Men Solid Leather Formal Monks',
 'Men Solid Formal Leather Loafers',
 'Men Solid Leather Formal Loafers',
 'Men HOVR Sonic 3 Running Shoes',
 'Men Leather Loafers',
 '',
 'Men Textured Leather Formal Loafers',
 'Men Leather Loafers',
 'Unisex Sneakers',
 'Men Solid Leather Formal Derbys',
 'Men Solid Leather Formal Oxfords',
 'Women Leather London Sneakers',
 'Leather Buckled Wedges',
 'Men Solid Leather Formal Brogues',
 'Women Leather Mid-Top Boots',
 'Men Float Ride Run 2.0',
 'Men Leather Derbys',
 'Women Basket Exotic Sneakers',
 'Men SKYTOP V Sneakers',
 'Men Derbys',
 'Men Solid Leather Formal Derbys',
 'Men Watts Pace Leather Derbys',
 'Men NITE JOGGER Sneakers',
 'Men Remix 2.0 Sportstyle Shoes',
 'Unisex Zig Kinetica 21 Running',
 'Men Liquify Running Shoes',
 'Men HOVR Guardian Shoes',
 'Men Solid NMD_R1 Sneakers',
 'Men AIR MAX INFINITY 2 Sneaker',
 'Men Solid Patent Leather Formal Loafers',
 'Men Solid Leather Formal Oxfords',
 'Men Solid Sneakers',
 'Men Running Shoes',
 'Unisex LEBRON Basketball Shoes',
 'Men Valsetz RTS 1.5 Trekking',
 'Men LEBRON 14 Basketball Shoes',
 'Men AIR ZOOM Running Shoes',
 'Men Sneakers',
 'TriBase Reign 2 Training Shoes',
 'Women Printed Sneakers',
 'Men SKECH-AIR STRATUS Sneakers',
 'Men LQDCELL Optic Shoes',
 'Unisex Textile Rise XT NETFIT 1 Baseball Shoes',
 'Men Solid Sneakers',
 'Women NMD_R1 PK Sneakers',
 'Unisex Leather Mexico 66 Sneakers',
 'Women Embellished Slim Heels',
 'Women Mid-Top Leather Heels',
 'Men Derbys Casual Shoes',
 'Men Solid Leather Formal Derbys',
 'Men Solid Leather Formal Monks',
 'Men Solid Formal Leather Loafers',
 'Men Solid Leather Formal Loafers',
 'Men HOVR Sonic 3 Running Shoes']

In [261]:
print(len(shoe_name))
print(len(price_of_shoe))
print(len(description_of_shoe))

150
150
150

In [263]:
#forming the dataframe
shoe=pd.DataFrame({})
shoe['shoe name']=shoe_name
shoe['price of shoe']=price_of_shoe
shoe['description of shoe']=description_of_shoe

In [264]:
df=shoe.head(100)

In [265]:
df

,shoe name,price of shoe,description of shoe
0,Regal,Rs. 6742Rs. 8990(25% OFF),Men Leather Loafers
1,Regal,Rs. 6742Rs. 8990(25% OFF),
2,J.FONTINI,Rs. 7990,Men Textured Leather Formal Loafers
3,J.FONTINI,Rs. 7990,Men Leather Loafers
4,Onitsuka Tiger,Rs. 10999,Unisex Sneakers
...,...,...,...
95,Florsheim,Rs. 6996Rs. 9995(30% OFF),Men Solid Leather Formal Derbys
96,ROSSO BRUNELLO,Rs. 7699Rs. 10999(30% OFF),Men Solid Leather Formal Monks
97,DAVINCHI,Rs. 7191Rs. 7990(10% OFF),Men Solid Formal Leather Loafers
98,ROSSO BRUNELLO,Rs. 7699Rs. 10999(30% OFF),Men Solid Leather Formal Loafers
99,UNDER ARMOUR,Rs. 10999,Men HOVR Sonic 3 Running Shoes