In [2]:
#using selenium for webscraping and also using the exception handling
import pandas as pd
import selenium
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException

In [3]:
#chromeweb browser is used
driver = webdriver.Chrome("Chromedriver.exe")

In [4]:
#ics website is used
url = 'https://archive.ics.uci.edu/'
driver.get(url)

In [5]:
#button is clicked
button = driver.find_elements_by_xpath('/html/body/table[1]/tbody/tr/td[2]/span[2]/a/font/b')[0]

In [6]:
button.click()

In [13]:
#value are webscraped
dataset_name=[]

try:

    names=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[1]')

    for i in names:

        dataset_name.append(i.text)

except NoSuchElementException:#handling no such element exception

    dataset_name.append('No details available')

print(len(dataset_name))


data_type1=[]

try:

    data_type=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[2]')

    for i in data_type:

        data_type1.append(i.text)

except NoSuchElementException:#handling no such element exception

    data_type1.append('No details available')

print(len(data_type1))

task1=[]

try:

    task=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[3]')

    for i in task:

        task1.append(i.text)

except NoSuchElementException:#handling no such element exception

    task1.append('No details available')

print(len(task1))


attribute_type1=[]

try:

    attribute_type=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[4]')

    for i in attribute_type:

        attribute_type1.append(i.text)

except NoSuchElementException:#handling no such element exception

    attribute_type1.append('No details available')

print(len(attribute_type1))


no_of_instance1=[]

try:

    no_of_instance=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[5]/p')

    for i in no_of_instance:

        no_of_instance1.append(i.text)

except NoSuchElementException:#handling no such element exception

    no_of_instance1.append('No details available')

print(len(no_of_instance1))


year1=[]

try:

    year=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[7]/p')

    for i in year:

        year1.append(i.text)

except NoSuchElementException:#handling no such element exception

    year1.append('No details available')

print(len(year1))


no_of_attribute1=[]

try:

    no_of_attribute=driver.find_elements_by_xpath('/html/body/table[2]/tbody/tr/td[2]/table[2]/tbody/tr/td[6]/p')

    for i in no_of_attribute:

        no_of_attribute1.append(i.text)

except NoSuchElementException:#handling no such element exception

    no_of_attribute1.append('No details available')

print(len(no_of_attribute))

#dataframe is used

df=pd.DataFrame({})
df['dataset_name']=dataset_name
df['data_type']=data_type1
df['task']=task1
df['attribute_type']=attribute_type1
df['no_of_instance']=no_of_instance1
df['no_of_attribute']=no_of_attribute1
df['year']=year1

df

df = df.drop(labels=0, axis=0)

df

589
589
589
589
589
589
589

,dataset_name,data_type,task,attribute_type,no_of_instance,no_of_attribute,year
1,Abalone,Multivariate,Classification,"Categorical, Integer, Real",4177,8,1995
2,Adult,Multivariate,Classification,"Categorical, Integer",48842,14,1996
3,Annealing,Multivariate,Classification,"Categorical, Integer, Real",798,38,
4,Anonymous Microsoft Web Data,,Recommender-Systems,Categorical,37711,294,1998
5,Arrhythmia,Multivariate,Classification,"Categorical, Integer, Real",452,279,1998
...,...,...,...,...,...,...,...
584,in-vehicle coupon recommendation,Multivariate,Classification,,12684,23,2020
585,Gait Classification,Multivariate,Classification,Real,48,321,2020
586,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
587,Wikipedia Math Essentials,Time-Series,Regression,Real,731,1068,2021
588,Synchronous Machine Data Set,Multivariate,Regression,Real,557,5,2021